# Generated by Django 5.2 on 2025-04-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_factory_year_alter_car_model_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
    ]
