# Generated by Django 5.2 on 2025-06-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='carinventory',
            name='car_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='carinventory',
            name='cars_count',
            field=models.IntegerField(),
        ),
    ]
