# Generated by Django 5.2 on 2025-06-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_rename_price_car_value_alter_carinventory_car_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinventory',
            old_name='car_value',
            new_name='cars_value',
        ),
    ]
